services:
  db-service:
    image: postgres:latest
    container_name: postgres-db-container
    restart: always
    environment:
      DB_NAME: ${CDB_NAME}
      DB_USER: ${CDB_USER}
      DB_PASSWORD: ${CDB_PASSWORD}
      DB_PORT: ${CDB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'

  backend-service:
    build:
      context: ./BE-membership-connect
      dockerfile: Dockerfile
    container_name: backend-container
    depends_on:
      - db-service
    env_file:
      - .env
    ports:
      - '5000:5000'
    networks:
      - app-network

  frontend-service:
    build:
      context: ./FE-membership-connect
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=http://localhost:5000
    container_name: frontend-container
    ports:
      - '3000:80'
    depends_on:
      - backend-service
    networks:
      - app-network
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
