apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mc-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: backend-container
          image: acrmembershipconnect.azurecr.io/backend-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: 'Staging'
            - name: ASPNETCORE_URLS
              value: 'http://+:5000'
            - name: ConnectionStrings__DefaultConnection
              value: 'Host=postgres-service;Port=5432;Database=container-db;Username=postgres;Password=postgres;'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mc-namespace
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
