apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mc-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # Base64 encoded 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM= # Base64 encoded 'postgres'
  POSTGRES_DB: Y29udGFpbmVyLWRi # Base64 encoded 'container-db'
