name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - 'BE-membership-connect/**'
  pull_request:
    paths:
      - 'BE-membership-connect/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # Build the project
      - name: Build .NET project
        run: |
          cd BE-membership-connect
          dotnet restore
          dotnet publish -c Release -o ./publish

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: acrmembershipconnect.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push the backend Docker image
      - name: Build and push Backend image
        run: |
          docker build -t acrmembershipconnect.azurecr.io/backend-image:latest -f BE-membership-connect/Dockerfile BE-membership-connect
          docker push acrmembershipconnect.azurecr.io/backend-image:latest
