name: Deploy to Local Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Check out
      - uses: actions/checkout@v2  # Check out the repository

      # Apply Kubernetes manifests to your local cluster
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/namespace.yml
          kubectl apply -f kubernetes/backend-deployment.yml
          kubectl apply -f kubernetes/frontend-deployment.yml
          kubectl apply -f kubernetes/postgres-statefulset.yml
          kubectl apply -f kubernetes/ingress.yml
          kubectl apply -f kubernetes/secret.yml
