name: Deploy to Kubernetes Cluster

on:
  workflow_run:
    workflows: ["Backend CI/CD Pipeline", "Frontend CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Check out the code
      - name: Check out the repository
        uses: actions/checkout@v2

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      # Ensure the cluster is accessible
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/namespace.yml
          kubectl apply -f kubernetes/backend-deployment.yml
          kubectl apply -f kubernetes/frontend-deployment.yml
          kubectl apply -f kubernetes/postgres-statefulset.yml
          kubectl apply -f kubernetes/ingress.yml
          kubectl apply -f kubernetes/secret.yml
