name: Frontend CI/CD Pipeline

on:
  push:
    paths:
      - 'FE-membership-connect/**'
  pull_request:
    paths:
      - 'FE-membership-connect/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Node.js and Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Install dependencies and build the React app
      - name: Build React app
        run: |
          cd FE-membership-connect
          yarn install --frozen-lockfile
          yarn build

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: acrmembershipconnect.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push the frontend Docker image
      - name: Build and push Frontend image
        run: |
          docker build -t acrmembershipconnect.azurecr.io/frontend-image:latest -f FE-membership-connect/Dockerfile ./FE-membership-connect
          docker push acrmembershipconnect.azurecr.io/frontend-image:latest
